version: "3.5"

services:
  web:
    env_file: .env
    build: 
      context: ./
      dockerfile: ./Dockerfile
      args:
        WG_ADDRESS: ${WG_ADDRESS}
    cap_add: 
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped 
    volumes:
      - /lib/modules:/lib/modules
      - ./src:/opt/wgdashboard
      - ./config:/root/wireguard
    ports:
      - 10086:10086
      - 51821:51820/udp
