version: "3.5"

services:
  web:
    env_file: .env
    build: 
      context: ./
      dockerfile: ./Dockerfile
      args:
        WG_ADDRESS: ${WG_ADDRESS}
        WG_LISTENPORT: ${WG_LISTENPORT}
    cap_add: 
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped 
    volumes:
      - /lib/modules:/lib/modules
      - ./src:/opt/wgdashboard
    ports:
      - 10086:10086
      - 51820:${WG_LISTENPORT}/udp
