version: "3.5"

services:
  web:
    env_file: .env
    build: 
      context: ./
      dockerfile: ./Dockerfile
      args:
        WG_ADDRESS: ${WG_ADDRESS}
        WG_LISTENPORT: ${WG_LISTENPORT}
    command: /opt/WGDashboard/src/wgd.sh debug
    restart: unless-stopped 
    ports:
      - 10086:10086
      - ${WG_LISTENPORT}:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
